# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install


# Expose the port your app runs on
EXPOSE 

# Define the command to run your Node.js application
CMD ["npx", "nodemon", "src/server.js"]


